apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: operator
  name: {{ include "operator.fullname" . }}-decofile-viewer-role
rules:
- apiGroups:
  - deco.sites.deco.sites
  resources:
  - decofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deco.sites.deco.sites
  resources:
  - decofiles/status
  verbs:
  - get