apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: operator
  name: {{ .Release.Name }}-decofile-editor-role
rules:
- apiGroups:
  - deco.sites.deco.sites
  resources:
  - decofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deco.sites.deco.sites
  resources:
  - decofiles/status
  verbs:
  - get