apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: operator
  name: {{ .Release.Name }}-decofile-admin-role
rules:
- apiGroups:
  - deco.sites.deco.sites
  resources:
  - decofiles
  verbs:
  - '*'
- apiGroups:
  - deco.sites.deco.sites
  resources:
  - decofiles/status
  verbs:
  - get